-- @ScriptType: ModuleScript
local PassiveSkillData = {}

PassiveSkillData.Trees = {}
PassiveSkillData.Passives = {}

local function AddPassives(standName, passivesList)
	PassiveSkillData.Trees[standName] = { Nodes = {} }
	PassiveSkillData.Passives[standName] = {}
	for i, pData in ipairs(passivesList) do
		local key = pData.Key
		table.insert(PassiveSkillData.Trees[standName].Nodes, { Type = "Passive", Key = key, Cost = pData.Cost or 2 })
		PassiveSkillData.Passives[standName][key] = {
			Name = pData.Name,
			Desc = pData.Desc,
			Type = "Passive",
			Effects = pData.Effects or {}
		}
	end
end

AddPassives("Purple Haze", {
	{Key="DeadlyVirus", Name="Deadly Virus", Desc="Upgrades Sick effects to Poison.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}},
	{Key="FleshEating", Name="Flesh Eating", Desc="Upgrades Poison effects to Plague.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Poison", To = "Plague"}}},
	{Key="CorrosiveMist", Name="Corrosive Mist", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="Hazmat", Name="Hazmat Shield", Desc="Reduces incoming damage by 15%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}
})
AddPassives("Green Day", {
	{Key="MoldSpores", Name="Mold Spores", Desc="Upgrades Sick effects to Poison.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}},
	{Key="DownwardDecay", Name="Downward Decay", Desc="Upgrades Poison effects to Decay.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Poison", To = "Decay"}}},
	{Key="FleshRot", Name="Flesh Rot", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="HighAltitude", Name="High Altitude", Desc="Reduces incoming negative status durations by 1 turn.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}
})
AddPassives("Brain Storm", {
	{Key="ToxinTouch", Name="Toxin Touch", Desc="Upgrades Sick effects to Poison.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}},
	{Key="CellularRuin", Name="Cellular Ruin", Desc="Upgrades Poison effects to Necrosis.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Poison", To = "Necrosis"}}},
	{Key="InternalDecay", Name="Internal Decay", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}}
})

AddPassives("Magician's Red", {
	{Key="IntenseHeat", Name="Intense Heat", Desc="Upgrades Burn effects to Scorch.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}},
	{Key="WhiteHot", Name="White Hot", Desc="Upgrades Scorch effects to Rupture.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Scorch", To = "Rupture"}}},
	{Key="PiercingFlames", Name="Piercing Flames", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}}
})
AddPassives("The Sun", {
	{Key="SolarHeat", Name="Solar Heat", Desc="Upgrades Burn effects to Scorch.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}},
	{Key="Supernova", Name="Supernova", Desc="Upgrades Scorch effects to Rupture.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Scorch", To = "Rupture"}}},
	{Key="UnbearableRays", Name="Unbearable Rays", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}}
})
AddPassives("Speed King", {
	{Key="LocalizedHeat", Name="Localized Heat", Desc="Upgrades Burn effects to Scorch.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}},
	{Key="MeltingPoint", Name="Melting Point", Desc="Upgrades Scorch effects to Rupture.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Scorch", To = "Rupture"}}},
	{Key="ArmorMelt", Name="Armor Melt", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="HeatResistance", Name="Heat Resistance", Desc="Reduces incoming fire and explosive damage by 15%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"Fire", "Explosive"}}}}
})

AddPassives("White Album", {
	{Key="FlashFreeze", Name="Flash Freeze", Desc="Upgrades Chill effects to Frost.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Chill", To = "Frost"}}},
	{Key="AbsoluteZero", Name="Absolute Zero", Desc="Upgrades Frost effects to Frostbite.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Frost", To = "Frostbite"}}},
	{Key="BitingCold", Name="Biting Cold", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="IceArmor", Name="Ice Armor", Desc="Reduces incoming physical damage by 15%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"Physical"}}}}
})
AddPassives("Horus", {
	{Key="ColdSnap", Name="Cold Snap", Desc="Upgrades Chill effects to Frost.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Chill", To = "Frost"}}},
	{Key="SubZero", Name="Sub-Zero", Desc="Upgrades Frost effects to Frostbite.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Frost", To = "Frostbite"}}},
	{Key="PiercingIce", Name="Piercing Ice", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="ColdBlooded", Name="Cold Blooded", Desc="Reduces incoming freeze and stun durations by 1 turn.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"Freeze", "Stun"}}}}
})
AddPassives("Born This Way", {
	{Key="ChillingWind", Name="Chilling Wind", Desc="Upgrades Chill effects to Frost.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Chill", To = "Frost"}}},
	{Key="DeepFreeze", Name="Deep Freeze", Desc="Upgrades Frost effects to Frostbite.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Frost", To = "Frostbite"}}},
	{Key="FreezingGale", Name="Freezing Gale", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="WinterJacket", Name="Winter Jacket", Desc="Reduces incoming damage by 15%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}},
	{Key="Unstoppable", Name="Unstoppable", Desc="Reduces incoming speed debuff durations by 1 turn.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"SpeedDebuff"}}}}
})

AddPassives("Metallica", {
	{Key="IronSands", Name="Iron Sands", Desc="Upgrades Bleed effects to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}},
	{Key="RazorEdge", Name="Razor Edge", Desc="Upgrades Hemorrhage effects to Rupture.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Hemorrhage", To = "Rupture"}}},
	{Key="InternalBleeding", Name="Internal Bleeding", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="IronBlood", Name="Iron Blood", Desc="Reduces incoming damage by 15%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}},
	{Key="MagneticPull", Name="Magnetic Pull", Desc="Increases the duration of bleed effects by 1 turn.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed", "Hemorrhage"}}}}
})
AddPassives("King Crimson", {
	{Key="DeepCut", Name="Deep Cut", Desc="Upgrades Bleed effects to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}},
	{Key="FatedWound", Name="Fated Wound", Desc="Upgrades Hemorrhage effects to Rupture.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Hemorrhage", To = "Rupture"}}},
	{Key="PiercingStrike", Name="Piercing Strike", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="TimeShield", Name="Time's Shield", Desc="Reduces incoming damage by 15%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}},
	{Key="EpitaphInsight", Name="Epitaph Insight", Desc="Reduces incoming negative status durations by 1 turn.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}
})
AddPassives("Silver Chariot", {
	{Key="SharpBlade", Name="Sharp Blade", Desc="Upgrades Bleed effects to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}},
	{Key="MasterSwordsman", Name="Master Swordsman", Desc="Upgrades Hemorrhage effects to Rupture.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Hemorrhage", To = "Rupture"}}},
	{Key="ArmorPiercing", Name="Armor Piercing", Desc="Your status effects bypass 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="ChobhamArmor", Name="Chobham Armor", Desc="Reduces incoming damage by 15%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}
})

AddPassives("Wonder of U", {
	{Key="InevitableCalamity", Name="Inevitable Calamity", Desc="Upgrades Status Random to Calamity.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Status_Random", To = "Calamity"}}},
	{Key="LogicDefying", Name="Logic Defying", Desc="Calamity bypasses 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="Misfortune", Name="Misfortune", Desc="Increases the duration of status effects you inflict by 1 turn.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}},
	{Key="SafeDistance", Name="Safe Distance", Desc="Reduces incoming damage by 20%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}},
	{Key="Untouchable", Name="Untouchable", Desc="Reduces incoming negative status durations by 1 turn.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}
})
AddPassives("D4C Love Train", {
	{Key="HolyMisfortune", Name="Holy Misfortune", Desc="Upgrades Status Random to Calamity.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Status_Random", To = "Calamity"}}},
	{Key="PiercingLight", Name="Piercing Light", Desc="Calamity bypasses 100% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 100}}},
	{Key="DimensionalWall", Name="Dimensional Wall", Desc="Reduces incoming damage by 20%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}},
	{Key="LuckRedirection", Name="Luck Redirection", Desc="Reduces incoming negative status durations by 1 turn.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}},
	{Key="ParallelResilience", Name="Parallel Resilience", Desc="Increases the duration of status effects you inflict by 1 turn.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}}
})

AddPassives("Hermit Purple", { {Key="HamonMastery", Name="Hamon Mastery", Desc="Upgrades Burn to Scorch.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="ThickVines", Name="Thick Vines", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Beach Boy", { {Key="DeepHook", Name="Deep Hook", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="ToughLine", Name="Tough Line", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Aerosmith", { {Key="IncendiaryRounds", Name="Incendiary Rounds", Desc="Upgrades Burn to Scorch.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="EvasiveFlight", Name="Evasive Flight", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Tower of Gray", { {Key="DeepCut", Name="Deep Cut", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="HighSpeed", Name="High Speed", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Emperor", { {Key="SteelyResolve", Name="Steely Resolve", Desc="Reduces incoming stun durations by 1 turn.", Cost=2, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"Stun"}}}}, {Key="PiercingBullets", Name="Piercing Bullets", Desc="Bypasses 10% of enemy armor.", Cost=2, Effects = {{Type = "ArmorBypass", Value = 10}}} })
AddPassives("Harvest", { {Key="ToxicSting", Name="Toxic Sting", Desc="Upgrades Sick to Poison.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}}, {Key="SwarmShield", Name="Swarm Shield", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Soft Machine", { {Key="Deflated", Name="Deflated", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="SharpRapier", Name="Sharp Rapier", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}} })
AddPassives("Little Feet", { {Key="TinyTarget", Name="Tiny Target", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="ToxicTrap", Name="Toxic Trap", Desc="Upgrades Sick to Poison.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}} })
AddPassives("Goo Goo Dolls", { {Key="SharpClaws", Name="Sharp Claws", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="RatSwarm", Name="Rat Swarm", Desc="Increases status duration by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}} })
AddPassives("Manhattan Transfer", { {Key="SilentWind", Name="Silent Wind", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="PerfectAim", Name="Perfect Aim", Desc="Bypasses 10% of enemy armor.", Cost=2, Effects = {{Type = "ArmorBypass", Value = 10}}} })
AddPassives("Survivor", { {Key="SparkSurge", Name="Spark Surge", Desc="Increases confusion duration by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="NumbNerves", Name="Numb Nerves", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Tohth", { {Key="Forewarning", Name="Forewarning", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="FatedFate", Name="Fated Fate", Desc="Increases stun duration by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}} })
AddPassives("Six Pistols", { {Key="RicochetMastery", Name="Ricochet Mastery", Desc="Bypasses 10% of enemy armor.", Cost=2, Effects = {{Type = "ArmorBypass", Value = 10}}}, {Key="QuickReload", Name="Quick Reload", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Marilyn Manson", { {Key="DebtCollector", Name="Debt Collector", Desc="Increases debuff durations by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="ThickSkin", Name="Thick Skin", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("TATOO YOU!", { {Key="DeepCut", Name="Deep Cut", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="CanvasHide", Name="Canvas Hide", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Tubular Bells", { {Key="MetalBalloon", Name="Metal Balloon", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="SteelFrame", Name="Steel Frame", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Hey Ya!", { {Key="PureLuck", Name="Pure Luck", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="Encouragement", Name="Encouragement", Desc="Reduces incoming negative status durations by 1.", Cost=2, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Tomb of the Boom", { {Key="IronSand", Name="Iron Sand", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="MagneticShield", Name="Magnetic Shield", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Wired", { {Key="BarbedHook", Name="Barbed Hook", Desc="Increases stun duration by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="PuddleHide", Name="Puddle Hide", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Oh! Lonesome Me", { {Key="Constrictor", Name="Constrictor", Desc="Increases stun duration by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="SplitBody", Name="Split Body", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Canine Style", { {Key="WireTrap", Name="Wire Trap", Desc="Increases stun duration by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="ApplePeel", Name="Apple Peel", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}} })
AddPassives("Fun Fun Fun", { {Key="AboveAdvantage", Name="Above Advantage", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="SharpNeedles", Name="Sharp Needles", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}} })
AddPassives("California King Bed", { {Key="MemoryLoss", Name="Memory Loss", Desc="Increases debuff duration by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="SoftMattress", Name="Soft Mattress", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Paper Moon King", { {Key="PaperCuts", Name="Paper Cuts", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="Illusionary", Name="Illusionary", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Space Trucking", { {Key="CardShield", Name="Card Shield", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="PaperCut", Name="Paper Cut", Desc="Upgrades Bleed to Hemorrhage.", Cost=2, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}} })
AddPassives("Milagro Man", { {Key="CursedCash", Name="Cursed Cash", Desc="Increases debuff duration by 1.", Cost=2, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="WealthShield", Name="Wealth Shield", Desc="Reduces incoming damage by 10%.", Cost=2, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })

AddPassives("Hierophant Green", { {Key="CoiledNet", Name="Coiled Net", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="SharpEmeralds", Name="Sharp Emeralds", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="TrapSetter", Name="Trap Setter", Desc="Increases stun duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}} })
AddPassives("Echoes Act 1", { {Key="EchoChamber", Name="Echo Chamber", Desc="Increases confusion duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="SoundBarrier", Name="Sound Barrier", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="SwiftFlight", Name="Swift Flight", Desc="Reduces incoming negative status durations by 1.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Ebony Devil", { {Key="Hatred", Name="Hatred", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="VoodooCurse", Name="Voodoo Curse", Desc="Increases status duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}}, {Key="DollBody", Name="Doll Body", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Lovers", { {Key="DeepRooted", Name="Deep Rooted", Desc="Increases confusion duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="Parasite", Name="Parasite", Desc="Upgrades Sick to Poison.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}}, {Key="Microscopic", Name="Microscopic", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Aqua Necklace", { {Key="HighPressure", Name="High Pressure", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="SteamForm", Name="Steam Form", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="InternalDamage", Name="Internal Damage", Desc="Bypasses 15% of enemy armor.", Cost=3, Effects = {{Type = "ArmorBypass", Value = 15}}} })
AddPassives("Enigma", { {Key="PaperShield", Name="Paper Shield", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="DeepFear", Name="Deep Fear", Desc="Increases debuff duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="SharpEdges", Name="Sharp Edges", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}} })
AddPassives("Man in the Mirror", { {Key="ShardToss", Name="Shard Toss", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="MirrorWorld", Name="Mirror World", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="Reflection", Name="Reflection", Desc="Reduces incoming negative status durations by 1.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Jumping Jack Flash", { {Key="DeepChill", Name="Deep Chill", Desc="Upgrades Chill to Frost.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Chill", To = "Frost"}}}, {Key="ZeroG", Name="Zero G", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="Centrifuge", Name="Centrifuge", Desc="Bypasses 15% of enemy armor.", Cost=3, Effects = {{Type = "ArmorBypass", Value = 15}}} })
AddPassives("Limp Bizkit", { {Key="InvisibleBites", Name="Invisible Bites", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="GhostlyForm", Name="Ghostly Form", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="SwarmAttack", Name="Swarm Attack", Desc="Increases bleed duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}} })
AddPassives("The Fool", { {Key="SandArmor", Name="Sand Armor", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="AbrasiveSand", Name="Abrasive Sand", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="Glider", Name="Glider", Desc="Reduces incoming negative status durations by 1.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Moody Blues", { {Key="Rewind", Name="Rewind", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="Playback", Name="Playback", Desc="Reduces incoming negative status durations by 1.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="HeavyStrike", Name="Heavy Strike", Desc="Bypasses 15% of enemy armor.", Cost=3, Effects = {{Type = "ArmorBypass", Value = 15}}} })
AddPassives("Cream Starter", { {Key="AcidicFoam", Name="Acidic Foam", Desc="Upgrades Sick to Acid.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Acid"}}}, {Key="FleshPatch", Name="Flesh Patch", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="Corrosive", Name="Corrosive", Desc="Bypasses 15% of enemy armor.", Cost=3, Effects = {{Type = "ArmorBypass", Value = 15}}} })
AddPassives("In a Silent Way", { {Key="SharpSound", Name="Sharp Sound", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="SoundCamo", Name="Sound Camouflage", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="Deafening", Name="Deafening", Desc="Increases bleed duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}} })
AddPassives("Boku no Rhythm wo Kiitekure", { {Key="HighExplosive", Name="High Explosive", Desc="Upgrades Burn to Scorch.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="PinTrap", Name="Pin Trap", Desc="Increases stun duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="Clockwork", Name="Clockwork", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}} })
AddPassives("Chocolate Disco", { {Key="GridArmor", Name="Grid Armor", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="TeleportEvasion", Name="Teleport Evasion", Desc="Reduces incoming negative status durations by 1.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="PrecisionDrop", Name="Precision Drop", Desc="Increases confusion duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}} })
AddPassives("King Nothing", { {Key="ScentTrack", Name="Scent Tracking", Desc="Reduces incoming negative status durations by 1.", Cost=3, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="PuzzleBody", Name="Puzzle Body", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="SharpPieces", Name="Sharp Pieces", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}} })
AddPassives("Walking Heart", { {Key="SharpHeels", Name="Sharp Heels", Desc="Upgrades Bleed to Hemorrhage.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="WallWalker", Name="Wall Walker", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="DeepImpale", Name="Deep Impale", Desc="Increases bleed duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}} })
AddPassives("Love Love Deluxe", { {Key="HairShield", Name="Hair Shield", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="TightTangle", Name="Tight Tangle", Desc="Increases stun duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="Chokehold", Name="Chokehold", Desc="Bypasses 15% of enemy armor.", Cost=3, Effects = {{Type = "ArmorBypass", Value = 15}}} })
AddPassives("Doobie Wah!", { {Key="SuffocatingWind", Name="Suffocating Wind", Desc="Upgrades Burn to Scorch.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="TornadoShield", Name="Tornado Shield", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="Relentless", Name="Relentless", Desc="Bypasses 15% of enemy armor.", Cost=3, Effects = {{Type = "ArmorBypass", Value = 15}}} })
AddPassives("Blue Hawaii", { {Key="MindControl", Name="Mind Control", Desc="Increases confusion duration by 1.", Cost=3, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="RelentlessZombie", Name="Relentless Zombie", Desc="Reduces incoming damage by 10%.", Cost=3, Effects = {{Type = "DamageReduction", Value = 10, Elements = {"All"}}}}, {Key="BloodInfection", Name="Blood Infection", Desc="Upgrades Sick to Poison.", Cost=3, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}} })

AddPassives("Sticky Fingers", { {Key="ZipperArmor", Name="Zipper Armor", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="DeepZip", Name="Deep Zip", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="UnzipDeflect", Name="Unzip Deflect", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="Dismember", Name="Dismember", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Stone Free", { {Key="StringMesh", Name="String Mesh", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="SharpThread", Name="Sharp Thread", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="MobiusStrip", Name="Mobius Strip", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="DeepCut", Name="Deep Cut", Desc="Increases bleed duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}} })
AddPassives("Cream", { {Key="VoidArmor", Name="Void Armor", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="DeepVoid", Name="Deep Void", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="SurpriseAttack", Name="Surprise Attack", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}}, {Key="DimensionHide", Name="Dimension Hide", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Death 13", { {Key="Nightmare", Name="Nightmare", Desc="Increases confusion duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="DreamWorld", Name="Dream World", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="SharpScythe", Name="Sharp Scythe", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="DeepSleep", Name="Deep Sleep", Desc="Increases stun duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}} })
AddPassives("Geb", { {Key="DesertWater", Name="Desert Water", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="HighPressure", Name="High Pressure", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="Quicksand", Name="Quicksand", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="SharpCut", Name="Sharp Cut", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Red Hot Chili Pepper", { {Key="HighVoltage", Name="High Voltage", Desc="Increases stun duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="ElectricShield", Name="Electric Shield", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="FastCharge", Name="Fast Charge", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="Overcharge", Name="Overcharge", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("The Grateful Dead", { {Key="RapidAging", Name="Rapid Aging", Desc="Increases debuff duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="WitheredBody", Name="Withered Body", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="Desiccation", Name="Desiccation", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}}, {Key="OldAge", Name="Old Age", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Planet Waves", { {Key="MeteorArmor", Name="Meteor Armor", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="IntenseHeat", Name="Intense Heat", Desc="Upgrades Burn to Scorch.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="MeteorShower", Name="Meteor Shower", Desc="Increases burn duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Burn"}}}}, {Key="OrbitalDefense", Name="Orbital Defense", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Jail House Lock", { {Key="Amnesia", Name="Amnesia", Desc="Increases confusion duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="IronBars", Name="Iron Bars", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="ThreeMemories", Name="Three Memories", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="LockDown", Name="Lock Down", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}} })
AddPassives("Anubis", { {Key="DualWield", Name="Dual Wield", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="MindControl", Name="Mind Control", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="LearnedPattern", Name="Learned Pattern", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}}, {Key="SharpBlade", Name="Sharp Blade", Desc="Increases bleed duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}} })
AddPassives("Spice Girl", { {Key="RubberBody", Name="Rubber Body", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="Soften", Name="Soften", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="BounceBack", Name="Bounce Back", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="SharpStrike", Name="Sharp Strike", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Diver Down", { {Key="InternalShield", Name="Internal Shield", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="BoneRearrange", Name="Bone Rearrange", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="DeepStrike", Name="Deep Strike", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}}, {Key="PhaseShift", Name="Phase Shift", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Kiss", { {Key="DoubleSticker", Name="Double Sticker", Desc="Increases stun duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="StickerArmor", Name="Sticker Armor", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="ViolentMerge", Name="Violent Merge", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}}, {Key="PeelOff", Name="Peel Off", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Bad Company", { {Key="InfantryShield", Name="Infantry Shield", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="ApacheStrike", Name="Apache Strike", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="FiringSquad", Name="Firing Squad", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}}, {Key="TacticalRetreat", Name="Tactical Retreat", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("20th Century Boy", { {Key="Grounded", Name="Grounded", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="AbsoluteDefense", Name="Absolute Defense", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="Redirect", Name="Redirect", Desc="Increases stun duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="EarthArmor", Name="Earth Armor", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Catch the Rainbow", { {Key="WaterWalking", Name="Water Walking", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="SharpRain", Name="Sharp Rain", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="StormSlicer", Name="Storm Slicer", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}}, {Key="FluidForm", Name="Fluid Form", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Civil War", { {Key="GuiltArmor", Name="Guilt Armor", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="SinsOfThePast", Name="Sins of the Past", Desc="Increases confusion duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="Manifestation", Name="Manifestation", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="HeavyBurden", Name="Heavy Burden", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Ticket to Ride", { {Key="DivineProtection", Name="Divine Protection", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="TearBlade", Name="Tear Blade", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="MisfortuneDeflect", Name="Misfortune Deflect", Desc="Increases confusion duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="SaintBlessing", Name="Saint's Blessing", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Sugar Mountain", { {Key="BarkSkin", Name="Bark Skin", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="BurdenOfWealth", Name="Burden of Wealth", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="WoodTransform", Name="Wood Transform", Desc="Increases stun duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="GoldenTrade", Name="Golden Trade", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Paisley Park", { {Key="ElectronicShield", Name="Electronic Shield", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="Navigation", Name="Navigation", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="ShockTrap", Name="Shock Trap", Desc="Increases stun duration by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="PathResistance", Name="Path of Resistance", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Nut King Call", { {Key="NutArmor", Name="Nut Armor", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="Dismantle", Name="Dismantle", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="ScrewOff", Name="Screw Off", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="InternalDamage", Name="Internal Damage", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("I Am a Rock", { {Key="RockArmor", Name="Rock Armor", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="GravityPull", Name="Gravity Pull", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="SpikeRain", Name="Spike Rain", Desc="Upgrades Bleed to Hemorrhage.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="HeavyGravity", Name="Heavy Gravity", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Vitamin C", { {Key="SoftBody", Name="Soft Body", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="Liquefy", Name="Liquefy", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="MeltDown", Name="Melt Down", Desc="Upgrades Sick to Acid.", Cost=4, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Acid"}}}, {Key="AcidicTouch", Name="Acidic Touch", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}} })
AddPassives("Ozon Baby", { {Key="PressureCabin", Name="Pressure Cabin", Desc="Reduces incoming damage by 15%.", Cost=4, Effects = {{Type = "DamageReduction", Value = 15, Elements = {"All"}}}}, {Key="Depressurize", Name="Depressurize", Desc="Increases debuff durations by 1.", Cost=4, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="CrushingPressure", Name="Crushing Pressure", Desc="Bypasses 20% of enemy armor.", Cost=4, Effects = {{Type = "ArmorBypass", Value = 20}}}, {Key="AirPocket", Name="Air Pocket", Desc="Reduces incoming negative status durations by 1.", Cost=4, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })

AddPassives("Killer Queen", { {Key="ExplosiveArmor", Name="Explosive Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="IntenseBlast", Name="Intense Blast", Desc="Upgrades Burn to Scorch.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="DeepBurns", Name="Deep Burns", Desc="Increases burn duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Burn"}}}}, {Key="BombPlant", Name="Bomb Plant", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="UnseenBomber", Name="Unseen Bomber", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Crazy Diamond", { {Key="HardenedGlass", Name="Hardened Glass", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="WallRestore", Name="Wall Restore", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="FixUp", Name="Fix Up", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="PrecisionStrike", Name="Precision Strike", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="BloodTracker", Name="Blood Tracker", Desc="Increases bleed duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}} })
AddPassives("Gold Experience", { {Key="LifeArmor", Name="Life Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="SensoryOverload", Name="Sensory Overload", Desc="Increases confusion duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="TreeRoots", Name="Tree Roots", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="Vitality", Name="Vitality", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="Overgrowth", Name="Overgrowth", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })
AddPassives("Whitesnake", { {Key="MeltYourHeart", Name="Melt Your Heart", Desc="Upgrades Sick to Acid.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Acid"}}}, {Key="IllusionaryDefense", Name="Illusion Defense", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="DiscExtraction", Name="Disc Extraction", Desc="Increases debuff durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="MemoryLoss", Name="Memory Loss", Desc="Increases confusion duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="AcidicSludge", Name="Acidic Sludge", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })
AddPassives("Mandom", { {Key="TrueMan", Name="True Man", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="SixSeconds", Name="Six Seconds", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="Disorient", Name="Disorient", Desc="Increases debuff durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="Duelist", Name="Duelist", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="PerfectShot", Name="Perfect Shot", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })
AddPassives("Dirty Deeds Done Dirt Cheap", { {Key="DimensionalWall", Name="Dimensional Wall", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="ParallelSelf", Name="Parallel Self", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="SpongeParadox", Name="Sponge Paradox", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="DimensionHop", Name="Dimension Hop", Desc="Increases bleed duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}}, {Key="UnseenStrike", Name="Unseen Strike", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })
AddPassives("Scary Monsters", { {Key="ApexPredator", Name="Apex Predator", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="DinosaurScales", Name="Dinosaur Scales", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="InfectiousBite", Name="Infectious Bite", Desc="Upgrades Sick to Poison.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}}, {Key="PrimalEvolution", Name="Primal Evolution", Desc="Upgrades Poison to Infection.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Poison", To = "Infection"}}}, {Key="Fossilize", Name="Fossilize", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Tusk Act 1", { {Key="HardenedNails", Name="Hardened Nails", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="SpinningNail", Name="Spinning Nail", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="GoldenRectangle", Name="Golden Rectangle", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="RapidFire", Name="Rapid Fire", Desc="Increases status durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}}, {Key="SmallTarget", Name="Small Target", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Soft & Wet", { {Key="BubbleShield", Name="Bubble Shield", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="PlunderVision", Name="Plunder Vision", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="PlunderFriction", Name="Plunder Friction", Desc="Increases debuff durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="PoppingBubbles", Name="Popping Bubbles", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="Slippery", Name="Slippery", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Killer Queen (Part 8)", { {Key="BubbleArmor", Name="Bubble Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="IntenseBlast", Name="Intense Blast", Desc="Upgrades Burn to Scorch.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="DeepBurns", Name="Deep Burns", Desc="Increases burn duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Burn"}}}}, {Key="BombPlant", Name="Bomb Plant", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="UnseenBomber", Name="Unseen Bomber", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Awaking III Leaves", { {Key="VectorShield", Name="Vector Shield", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="VectorArrow", Name="Vector Arrow", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="TornadoSlash", Name="Tornado Slash", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="Repel", Name="Repel", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="AbsoluteVector", Name="Absolute Vector", Desc="Increases status durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}} })
AddPassives("Star Platinum", { {Key="SteelyResolve", Name="Steely Resolve", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="StarFinger", Name="Star Finger", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="DeepInhale", Name="Deep Inhale", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="PrecisionStrike", Name="Precision Strike", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="Unbreakable", Name="Unbreakable", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("The World", { {Key="VampireResilience", Name="Vampire Resilience", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="KnifeThrow", Name="Knife Throw", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="RoadRoller", Name="Road Roller", Desc="Increases bleed duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}}, {Key="TimeStopMastery", Name="Time Stop Mastery", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="ImmortalBlood", Name="Immortal Blood", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Weather Report", { {Key="CloudArmor", Name="Cloud Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="ToxicFrogs", Name="Toxic Frogs", Desc="Upgrades Sick to Poison.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}}, {Key="HeavyWeather", Name="Heavy Weather", Desc="Increases confusion duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="StormLightning", Name="Storm Lightning", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="ClearSkies", Name="Clear Skies", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Heaven's Door", { {Key="SafetyLock", Name="Safety Lock", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="PagePeel", Name="Page Peel", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="WrittenFate", Name="Written Fate", Desc="Increases debuff durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="RealityRewrite", Name="Reality Rewrite", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="Erasure", Name="Erasure", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("The Hand", { {Key="SpaceErasure", Name="Space Erasure", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="EraseDistance", Name="Erase Distance", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="VoidArmor", Name="Void Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="AbsoluteErasure", Name="Absolute Erasure", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="SwipeDeflect", Name="Swipe Deflect", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Star Platinum: The World", { {Key="SteelyResolve", Name="Steely Resolve", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="BearingShot", Name="Bearing Shot", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="HeartStop", Name="Heart Stop", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="PrecisionStrike", Name="Precision Strike", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="Unbreakable", Name="Unbreakable", Desc="Increases status durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}} })
AddPassives("Killer Queen BTD", { {Key="ExplosiveArmor", Name="Explosive Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="IntenseBlast", Name="Intense Blast", Desc="Upgrades Burn to Scorch.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="AirBomb", Name="Air Bomb", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="RewindFate", Name="Rewind Fate", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="DeepBurns", Name="Deep Burns", Desc="Increases burn duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Burn"}}}} })
AddPassives("C-Moon", { {Key="GravityShield", Name="Gravity Shield", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="SurfaceInversion", Name="Surface Inversion", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="CenterOfGravity", Name="Center of Gravity", Desc="Increases confusion duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="Repulsion", Name="Repulsion", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="InsideOut", Name="Inside Out", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })
AddPassives("Made in Heaven", { {Key="Acceleration", Name="Acceleration", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="SpeedSlice", Name="Speed Slice", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="AcceleratedKnives", Name="Accelerated Knives", Desc="Increases bleed duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Bleed"}}}}, {Key="TimeAcceleration", Name="Time Acceleration", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="UniverseReset", Name="Universe Reset", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Echoes Act 2", { {Key="SoundShield", Name="Sound Shield", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="Sizzle", Name="Sizzle", Desc="Upgrades Burn to Scorch.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="Boing", Name="Boing", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="Whoosh", Name="Whoosh", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="DeafeningSound", Name="Deafening Sound", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })
AddPassives("Echoes Act 3", { {Key="FreezeArmor", Name="Freeze Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="ThreeFreeze", Name="Three Freeze", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="HeavyGravity", Name="Heavy Gravity", Desc="Increases debuff durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="RhymeMaster", Name="Rhyme Master", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="GravityDeflect", Name="Gravity Deflect", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Gold Experience Requiem", { {Key="ApexArmor", Name="Apex Armor", Desc="Reduces incoming damage by 25%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 25, Elements = {"All"}}}}, {Key="TruthUnveiled", Name="Truth Unveiled", Desc="Bypasses 30% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 30}}}, {Key="InfiniteDeath", Name="Infinite Death", Desc="Increases confusion duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="ReturnToZero", Name="Return To Zero", Desc="Reduces incoming negative status durations by 2.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -2, Elements = {"All"}}}}, {Key="RequiemPower", Name="Requiem Power", Desc="Increases status durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}} })
AddPassives("Chariot Requiem", { {Key="SoulArmor", Name="Soul Armor", Desc="Reduces incoming damage by 25%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 25, Elements = {"All"}}}}, {Key="Transposition", Name="Transposition", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="Refraction", Name="Refraction", Desc="Increases confusion duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="Alteration", Name="Alteration", Desc="Bypasses 30% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 30}}}, {Key="RequiemWalk", Name="Requiem Walk", Desc="Reduces incoming negative status durations by 2.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -2, Elements = {"All"}}}} })
AddPassives("The World: High Voltage", { {Key="VampireResilience", Name="Vampire Resilience", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="KnifeThrow", Name="Knife Throw", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="WireTrap", Name="Wire Trap", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="TimeStopMastery", Name="Time Stop Mastery", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="ImmortalBlood", Name="Immortal Blood", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Star Platinum: Over Heaven", { {Key="HeavenlyArmor", Name="Heavenly Armor", Desc="Reduces incoming damage by 30%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 30, Elements = {"All"}}}}, {Key="RealityPierce", Name="Reality Pierce", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="RewriteTruth", Name="Rewrite Truth", Desc="Bypasses 30% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 30}}}, {Key="OverwriteDefense", Name="Overwrite Defense", Desc="Increases status durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}}, {Key="UniversalPower", Name="Universal Power", Desc="Reduces incoming negative status durations by 2.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -2, Elements = {"All"}}}} })
AddPassives("The World: Over Heaven", { {Key="HeavenlyArmor", Name="Heavenly Armor", Desc="Reduces incoming damage by 30%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 30, Elements = {"All"}}}}, {Key="HeavenlySmite", Name="Heavenly Smite", Desc="Upgrades Bleed to Hemmorhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="RewriteExistence", Name="Rewrite Existence", Desc="Bypasses 30% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 30}}}, {Key="OverwriteDefense", Name="Overwrite Defense", Desc="Increases status durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}}, {Key="UniversalPower", Name="Universal Power", Desc="Reduces incoming negative status durations by 2.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -2, Elements = {"All"}}}} })
AddPassives("King Crimson Requiem", { {Key="RequiemArmor", Name="Requiem Armor", Desc="Reduces incoming damage by 25%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 25, Elements = {"All"}}}}, {Key="DimensionalSlash", Name="Dimensional Slash", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="RealityMarble", Name="Reality Marble", Desc="Increases status durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}}, {Key="PiercingStrike", Name="Piercing Strike", Desc="Bypasses 30% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 30}}}, {Key="TimeShield", Name="Time's Shield", Desc="Reduces incoming negative status durations by 2.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -2, Elements = {"All"}}}} })
AddPassives("Tusk Act 2", { {Key="AurealArmor", Name="Aureal Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="MovingBullet", Name="Moving Bullet", Desc="Increases debuff durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="TrackingHole", Name="Tracking Hole", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="GoldenSpin", Name="Golden Spin", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="Wormhole", Name="Wormhole", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Tusk Act 3", { {Key="SpatialArmor", Name="Spatial Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="InfiniteSpin", Name="Infinite Spin", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="SpatialShot", Name="Spatial Shot", Desc="Increases confusion duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Confusion"}}}}, {Key="GoldenSpin", Name="Golden Spin", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}}, {Key="WormholeEvasion", Name="Wormhole Evasion", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}} })
AddPassives("Tusk Act 4", { {Key="InfiniteArmor", Name="Infinite Armor", Desc="Reduces incoming damage by 25%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 25, Elements = {"All"}}}}, {Key="CellularDestruction", Name="Cellular Destruction", Desc="Upgrades Sick to Poison.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Sick", To = "Poison"}}}, {Key="GoldenSpin", Name="Golden Spin", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="AbsoluteEnergy", Name="Absolute Energy", Desc="Bypasses 30% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 30}}}, {Key="InfiniteRotation", Name="Infinite Rotation", Desc="Reduces incoming negative status durations by 2.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -2, Elements = {"All"}}}} })
AddPassives("Soft & Wet: Go Beyond", { {Key="ExplosiveSpin", Name="Explosive Spin", Desc="Upgrades Burn to Scorch.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Burn", To = "Scorch"}}}, {Key="InvisibleBubble", Name="Invisible Bubble", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="LogicDefying", Name="Logic Defying", Desc="Bypasses 30% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 30}}}, {Key="SpinArmor", Name="Spin Armor", Desc="Reduces incoming damage by 25%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 25, Elements = {"All"}}}}, {Key="BeyondLogic", Name="Beyond Logic", Desc="Reduces incoming negative status durations by 2.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -2, Elements = {"All"}}}} })
AddPassives("Chiikawa", { {Key="UsagiArmor", Name="Usagi's Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="WeedWhacker", Name="Weed Whacker", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="RandomChaos", Name="Random Chaos", Desc="Increases status durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"All"}}}}, {Key="PajamaResilience", Name="Pajama Resilience", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="CryingRage", Name="Crying Rage", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })
AddPassives("Charmy Green", { {Key="EmeraldArmor", Name="Emerald Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="EmeraldFinger", Name="Emerald Finger", Desc="Upgrades Bleed to Hemorrhage.", Cost=5, Effects = {{Type = "StatusUpgrade", From = "Bleed", To = "Hemorrhage"}}}, {Key="GreenTrap", Name="Green Trap", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="Unbreakable", Name="Unbreakable", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="CharmyStrike", Name="Charmy Strike", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })
AddPassives("Steel Platinum", { {Key="SteelArmor", Name="Steel Armor", Desc="Reduces incoming damage by 20%.", Cost=5, Effects = {{Type = "DamageReduction", Value = 20, Elements = {"All"}}}}, {Key="DefenseBreaker", Name="Defense Breaker", Desc="Increases debuff durations by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Debuffs"}}}}, {Key="IronJail", Name="Iron Jail", Desc="Increases stun duration by 1.", Cost=5, Effects = {{Type = "OutgoingStatusDuration", Value = 1, Elements = {"Stun"}}}}, {Key="Unbreakable", Name="Unbreakable", Desc="Reduces incoming negative status durations by 1.", Cost=5, Effects = {{Type = "IncomingStatusDuration", Value = -1, Elements = {"All"}}}}, {Key="ShatteringFist", Name="Shattering Fist", Desc="Bypasses 25% of enemy armor.", Cost=5, Effects = {{Type = "ArmorBypass", Value = 25}}} })

return PassiveSkillData